In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [2]:
iris=load_iris()

# Logistic Regression

In [4]:
l_scores=cross_val_score(LogisticRegression(), iris.data, iris.target)
l_scores

C:\Users\F.Ghanadian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [5]:
np.average(l_scores)

0.9733333333333334

# Decision Tree


In [6]:
d_scores=cross_val_score(RandomForestClassifier(), iris.data, iris.target)
d_scores

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [7]:
np.average(d_scores)

0.96

# SVM

In [9]:
svm_scores=cross_val_score(SVC(), iris.data, iris.target)
svm_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [11]:
np.average(svm_scores)

0.9666666666666666

# Random Forest

In [12]:
rf_scores=cross_val_score(RandomForestClassifier(), iris.data, iris.target)
rf_scores

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [13]:
np.average(rf_scores)

0.9666666666666668